/**:
  ros__parameters:
    enable_object_filtering: true
    enable_pointcloud_filtering: true
    min_guaranteed_area_distance: 100.0  # [m] Minimum distance from the ego vehicle to guarantee area filtering
